In [6]:
import numpy as np
a=np.random.randint(1,100,24).reshape(6,4)
print(a)
print("\n")
print(np.sort(a)) # sort by row wise
print("\n")
print(np.sort(a,axis=0))
print("\n")
print(np.sort(a)[::-1])

[[13 80 37 57]
 [98 95 54 89]
 [99 13 18  9]
 [47 86 37 70]
 [99 14 50 11]
 [83 58 55 40]]


[[13 37 57 80]
 [54 89 95 98]
 [ 9 13 18 99]
 [37 47 70 86]
 [11 14 50 99]
 [40 55 58 83]]


[[13 13 18  9]
 [47 14 37 11]
 [83 58 37 40]
 [98 80 50 57]
 [99 86 54 70]
 [99 95 55 89]]


[[40 55 58 83]
 [11 14 50 99]
 [37 47 70 86]
 [ 9 13 18 99]
 [54 89 95 98]
 [13 37 57 80]]


In [9]:
b=np.array([1,2,3,4,5])
print(b)
print("\n")
print(np.append(b,10))


[1 2 3 4 5]


[ 1  2  3  4  5 10]


In [10]:
a

array([[13, 80, 37, 57],
       [98, 95, 54, 89],
       [99, 13, 18,  9],
       [47, 86, 37, 70],
       [99, 14, 50, 11],
       [83, 58, 55, 40]], dtype=int32)

In [14]:
np.append(a,np.ones((a.shape[0],1)),axis=1)

array([[13., 80., 37., 57.,  1.],
       [98., 95., 54., 89.,  1.],
       [99., 13., 18.,  9.,  1.],
       [47., 86., 37., 70.,  1.],
       [99., 14., 50., 11.,  1.],
       [83., 58., 55., 40.,  1.]])

In [16]:
a.shape

(6, 4)

In [17]:
# np.concatenate

c=[[1,2,3],[4,5,6]]
d=[[9,2,7],[5,0,3]]

np.concatenate((c,d),axis=0)

array([[1, 2, 3],
       [4, 5, 6],
       [9, 2, 7],
       [5, 0, 3]])