In [1]:
import numpy as np 
a1=np.random.random((3,3));
a1

array([[0.77898051, 0.59544845, 0.2558037 ],
       [0.52482072, 0.75587054, 0.4942198 ],
       [0.42181685, 0.68914935, 0.1614625 ]])

In [10]:
a1=np.array([
    [1,2,3],
    [3,4,5],
    [5,6,7]
])
np.max(a1)

np.int64(7)

In [11]:
np.min(a1)

np.int64(1)

In [12]:
# write max and min of each col/row
# 0->col 1->row

print(np.min(a1,axis=1))
print(np.max(a1,axis=1))
print(np.min(a1,axis=0))
print(np.max(a1,axis=0))
print(np.sum(a1,axis=1))
print(np.sum(a1,axis=0))
print(np.prod(a1,axis=1))
print(np.prod(a1,axis=0))

[1 3 5]
[3 5 7]
[1 2 3]
[5 6 7]
[ 6 12 18]
[ 9 12 15]
[  6  60 210]
[ 15  48 105]


In [16]:
print(np.mean(a1,axis=1))
print(np.var(a1,axis=1))
print(np.std(a1,axis=1))


[2. 4. 6.]
[0.66666667 0.66666667 0.66666667]
[0.81649658 0.81649658 0.81649658]


In [19]:
print(np.sin(a1))
print(np.cos(a1))
print(np.tan(a1))


[[ 0.84147098  0.90929743  0.14112001]
 [ 0.14112001 -0.7568025  -0.95892427]
 [-0.95892427 -0.2794155   0.6569866 ]]
[[ 0.54030231 -0.41614684 -0.9899925 ]
 [-0.9899925  -0.65364362  0.28366219]
 [ 0.28366219  0.96017029  0.75390225]]
[[ 1.55740772 -2.18503986 -0.14254654]
 [-0.14254654  1.15782128 -3.38051501]
 [-3.38051501 -0.29100619  0.87144798]]


In [20]:
# dot product 
a1=np.arange(12).reshape(3,4)
a2=np.arange(12,24).reshape(4,3)
np.dot(a1,a2)


array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [23]:
print(np.log(a1))
print(np.exp(a1))

[[      -inf 0.         0.69314718 1.09861229]
 [1.38629436 1.60943791 1.79175947 1.94591015]
 [2.07944154 2.19722458 2.30258509 2.39789527]]
[[1.00000000e+00 2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02 1.09663316e+03]
 [2.98095799e+03 8.10308393e+03 2.20264658e+04 5.98741417e+04]]


C:\Users\archi\AppData\Local\Temp\ipykernel_13848\1349568853.py:1: RuntimeWarning: divide by zero encountered in log
  print(np.log(a1))


In [ ]:
np.round(np.random.random((2*3)))

array([60., 93., 60., 10., 41., 55.])

In [33]:
a2=np.arange(0,10)
print(a2[0])
print(a2[-1])
print(a2[0:3])
print(a1[1,1])

0
9
[0 1 2]
5


In [34]:
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [35]:
a1[1][2]

np.int64(6)

In [36]:
a3=[
    [[1,2],[3,4]],
    [[5,6],[7,8]]
   ]

In [37]:
a3[1][0][1]

6

In [38]:
# slicing

a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [46]:
a1[0,:] # first row

array([0, 1, 2, 3])

In [47]:
a1[2,:] # 3rd row

array([ 8,  9, 10, 11])

In [45]:
a1[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [ ]:
a1[:,0] # 1st col

array([0, 4, 8])

In [50]:
a1[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [51]:
a1[1::2,::3]

array([[4, 7]])

In [52]:
a1[0:2,1:]

array([[1, 2, 3],
       [5, 6, 7]])

In [53]:
a3

[[[1, 2], [3, 4]], [[5, 6], [7, 8]]]

In [55]:
a4=np.arange(27).reshape(3,3,3)
print(a4)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [56]:
a4[1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [57]:
a4[0]

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [58]:
a4[2]

array([[18, 19, 20],
       [21, 22, 23],
       [24, 25, 26]])

In [59]:
a4[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [60]:
a4[0,1]

array([3, 4, 5])

In [61]:
a4[1,:,1]

array([10, 13, 16])

In [62]:
a4[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [63]:
a4[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

In [ ]:
a1 #2d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a2 #1d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a3 #3d

[[[1, 2], [3, 4]], [[5, 6], [7, 8]]]

In [ ]:
for i in a2: # each i is a single element
    print(i)

0
1
2
3
4
5
6
7
8
9


In [ ]:
for i in a1: # each i is a single row
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [ ]:
for i in a3: # each i is a single 2d array
    print(i)

[[1, 2], [3, 4]]
[[5, 6], [7, 8]]


In [ ]:
for i in np.nditer(a3): # converting a3 to a 1d array first
    print(i)

(array(1), array(5))
(array(2), array(6))
(array(3), array(7))
(array(4), array(8))


In [73]:
# reshaping
# transpose
print(a1)
print(np.transpose(a1))
a1.T

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [75]:
# ravel -> convert n dimentional array to 1 d array

np.ravel(a3)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [84]:
# stacking -> can stack 2 or more np arrays 
# horizontal
# vertical
a5=np.arange(12).reshape(3,4)
a6=np.arange(12,24).reshape(3,4)

a7=np.hstack((a5,a6))
a8=np.vstack((a5,a6))
print(a7)
print("\n")
print(a8)

[[ 0  1  2  3 12 13 14 15]
 [ 4  5  6  7 16 17 18 19]
 [ 8  9 10 11 20 21 22 23]]


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [88]:
# splitting -> opposite if stacking
print(np.hsplit(a7,2))
print("\n")
print(np.vsplit(a8,3))

[array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]]), array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])]


[array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]]), array([[16, 17, 18, 19],
       [20, 21, 22, 23]])]
