In [3]:
import numpy as np
a1=np.array([
    [2,4,6],
    [4,6,8],
    [6,8,10]
])

print(a1)

[[ 2  4  6]
 [ 4  6  8]
 [ 6  8 10]]


In [4]:
np.array(a1 *2)

array([[ 4,  8, 12],
       [ 8, 12, 16],
       [12, 16, 20]])

In [5]:
np.array(a1+2)

array([[ 4,  6,  8],
       [ 6,  8, 10],
       [ 8, 10, 12]])

In [6]:
np.array(a1-2)

array([[0, 2, 4],
       [2, 4, 6],
       [4, 6, 8]])

In [10]:
np.array(a1/2)

array([[1., 2., 3.],
       [2., 3., 4.],
       [3., 4., 5.]])

In [9]:
np.array(a1>9)

array([[False, False, False],
       [False, False, False],
       [False, False,  True]])

In [13]:
np.array(a1==3)

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

In [15]:
#vector operation
a1=np.array([
    [1,2,3],
    [3,4,5],
    [5,6,7]
])

a2=np.array([
    [1,2,3],
    [3,4,5],
    [5,6,7]
])


In [17]:
a3=np.array(a1+a2)
print(a3)

[[ 2  4  6]
 [ 6  8 10]
 [10 12 14]]


In [18]:
a4=np.array(a1-a2)
print(a4)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [19]:
a5=np.array(a1*a2)
print(a5)

[[ 1  4  9]
 [ 9 16 25]
 [25 36 49]]


In [20]:
a6=np.array(a1**a2)
print(a6)

[[     1      4     27]
 [    27    256   3125]
 [  3125  46656 823543]]
